### ISSUE TITLE
null pointer exception on world loading 

### ISSUE THREAD

**Issue by Biviho** [Henrykado/TheAetherBaubles#2]
hi, i've also got a null pointer exception during world loading without GroovyScript enabled

[the mighty log](https://mclo.gs/GUjd3Q1)

i'll look better into it to see if i can find what other mod cause this but it will take a while

**Comment by aking4125** [comment]
Confirmed: https://mclo.gs/mvzH7Kn

**Comment by Henrykado** [comment]
sorry for taking so long to reply, but i'm a little confused

does the game crash with just The Aether, Baubles, and this mod enabled?
or is an extra incompatible mod causing the crash

i'm also confused about why you mentioned GroovyScript, does it stop the crash from happening when it's enabled?

**Comment by MagmaSlime123** [comment]
> sorry for taking so long to reply, but i'm a little confused
> 
> does the game crash with just The Aether, Baubles, and this mod enabled? or is an extra incompatible mod causing the crash
> 
> i'm also confused about why you mentioned GroovyScript, does it stop the crash from happening when it's enabled?

You have new issues.
