### ISSUE TITLE
[Suggestion] Support for Lost Aether Content?

### ISSUE THREAD

**Issue by SonicX8000** [Henrykado/TheAetherBaubles#3]
https://legacy.curseforge.com/minecraft/mc-mods/aether-lost-content
Lost Aether Content adds in some accessories and I wonder if per chance that these could be converted into baubles.

![image](https://github.com/Henrykado/TheAetherBaubles/assets/36653806/cb60cb90-98dd-486a-93b1-f740bc092039)

The items are...

`lost_aether:phoenix_cape`
`lost_aether:sentry_shield`
`lost_aether:invisibility_gem`
`lost_aether:power_gloves`

**Comment by MagmaSlime123** [comment]
Dead mod.
