### ISSUE TITLE
Crash When Trying to Open Saved Game

### ISSUE THREAD

**Issue by sainguinkrist** [Henrykado/TheAetherBaubles#5]
Loads new worlds fine, but when I try to load into worlds I've previously made (with Aether Baubles installed), it crashes.

I've included my log.

![1mcaethercrash](https://github.com/Henrykado/TheAetherBaubles/assets/112531226/c6ce8ea8-df30-43df-8ec5-9082205a1d06)
[crash-2024-01-06_23.32.09-server.txt](https://github.com/Henrykado/TheAetherBaubles/files/13852353/crash-2024-01-06_23.32.09-server.txt)

Hope this helps figure it out, I consider Aether Baubles an essential mod for my pack.

**Comment by sainguinkrist** [comment]
It's now crashing when trying to create a new world as well.

**Comment by Henrykado** [comment]
Huh, could you send me the file of the world that's crashing?
For some reason i can't replicate the issue

**Comment by Henrykado** [comment]
The mods you are using too, in case you aren't just playing with just the 3 mods
