### ISSUE TITLE
Somnia Refreshed have on Github no Issus area and my Problem or Question is a GUI think

### ISSUE THREAD

**Issue by Titoo8899** [Henrykado/TheAetherBaubles#7]
Hi,
I have tested the Mod but I see then I sneak and click on a bed not the Clock in the GUI. What Configs must I change to see this?

Picture of the GUI:
This is your Design then I open a map on the first time
![2024-07-15_17 40 57](https://github.com/user-attachments/assets/f1822c06-821c-4125-9b9d-cf6d8e8c2b0c)

This have I hope
![3e514339d1704a78dc8407a104227ac610692cab](https://github.com/user-attachments/assets/e7c5a374-d5d6-4b26-9699-a7923c6f84cc)

**Comment by Titoo8899** [comment]
I have check then you sneak and click on a Bed to open the GUI the GUI open with no Clock (Picture 1) then I with a clock in the hand on a bed click to open the GUI the Clock is see (Picture 2). Can you change this and add the Clock and the times number then we have the cursor on a word switch every time see.

**Comment by Henrykado** [comment]
> Can you change this and add the Clock and the times number then we have the cursor on a word switch every time see.

Sorry but I don't really understand what you're trying to say, are you telling me to add an option to disable needing to be holding a clock when accessing the menu to see the current time and the buttons' hover text?

**Comment by Titoo8899** [comment]
Hi,
 I mean only the Original GUI what only open with a clock in the hand have a Clock (timer) in the middle and the buttons have then I with my mouse on this will click the time of day (see Picture 2 my mouse is on Midnight and then I on this button was it show me a time not the word). Your change with sneak and press a bed (see Picture 1) is cool but I hope you can add the 
Clock (Timer) in the middle and the times then I was with my mouse on a hover text.

**Comment by Titoo8899** [comment]
I find the design of the Original GUI of this mod every time nice but only the Hover text with the time and the Clock (timer) in the middle is what I miss in the GUI then I open it with sneak and click and I have hope you can add this little thinks for the next update.

**Comment by Henrykado** [comment]
To see the timer in the menu (and the buttons' hover text) you need to right click the bed while sneaking _and_ holding the clock at the same time

**Comment by Titoo8899** [comment]
Okay, but can you this change. I will only Sneak and on a bed click to see this the Clock in the hand find I not so good. I hope you can change this or a option add to this mod.

**Comment by Titoo8899** [comment]
thanks for the Update. The new Config what in Version 1.0.1 you have create works fine and have all thinks what I have miss. Thanks now can I good play.
