### ISSUE TITLE
After updating to the latest version, the mod crashes the server on startup

### ISSUE THREAD

**Issue by mahghuuuls** [Henrykado/TheAetherBaubles#9]
I have a server with the mod, when I updated the mod to the latest version, the server crashes on startup. It does not crashes the client. 

[crash-2024-11-30_17.27.43-server.txt](https://github.com/user-attachments/files/17966835/crash-2024-11-30_17.27.43-server.txt)

**Comment by beltxd** [comment]
I have this exact same issue as well.

**Comment by Henrykado** [comment]
Sorry for not answering. Will look into it

**Comment by Henrykado** [comment]
Fixed in the next update
